# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/carlos/workspace/TINY_NETWORK_TOOLS_PYQT5/uiform/MainUi.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(957, 758)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.comboBoxProtocal = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxProtocal.setObjectName("comboBoxProtocal")
        self.comboBoxProtocal.addItem("")
        self.comboBoxProtocal.addItem("")
        self.horizontalLayout.addWidget(self.comboBoxProtocal)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.comboBoxMode = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxMode.setObjectName("comboBoxMode")
        self.comboBoxMode.addItem("")
        self.comboBoxMode.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBoxMode)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_13.addWidget(self.label_11)
        self.comboBoxEthList = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxEthList.setObjectName("comboBoxEthList")
        self.horizontalLayout_13.addWidget(self.comboBoxEthList)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEditLocalIp = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditLocalIp.setObjectName("lineEditLocalIp")
        self.horizontalLayout_3.addWidget(self.lineEditLocalIp)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lineEditLocalPort = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditLocalPort.setObjectName("lineEditLocalPort")
        self.horizontalLayout_4.addWidget(self.lineEditLocalPort)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButtonConnect = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonConnect.setObjectName("pushButtonConnect")
        self.horizontalLayout_5.addWidget(self.pushButtonConnect)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButtonDisconnect = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonDisconnect.setObjectName("pushButtonDisconnect")
        self.horizontalLayout_6.addWidget(self.pushButtonDisconnect)
        self.pushButtonWriteIp = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonWriteIp.setObjectName("pushButtonWriteIp")
        self.horizontalLayout_6.addWidget(self.pushButtonWriteIp)
        self.pushButtonAppIp = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonAppIp.setObjectName("pushButtonAppIp")
        self.horizontalLayout_6.addWidget(self.pushButtonAppIp)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.groupBoxClientList = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxClientList.setObjectName("groupBoxClientList")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBoxClientList)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tableWidgetClientList = QtWidgets.QTableWidget(self.groupBoxClientList)
        self.tableWidgetClientList.setObjectName("tableWidgetClientList")
        self.tableWidgetClientList.setColumnCount(3)
        self.tableWidgetClientList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetClientList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetClientList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetClientList.setHorizontalHeaderItem(2, item)
        self.verticalLayout_7.addWidget(self.tableWidgetClientList)
        self.verticalLayout_6.addWidget(self.groupBoxClientList)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.radioButtonRecASCII = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButtonRecASCII.setChecked(True)
        self.radioButtonRecASCII.setObjectName("radioButtonRecASCII")
        self.horizontalLayout_10.addWidget(self.radioButtonRecASCII)
        self.radioButtonRecHex = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButtonRecHex.setObjectName("radioButtonRecHex")
        self.horizontalLayout_10.addWidget(self.radioButtonRecHex)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.checkBoxWordWrap = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxWordWrap.setObjectName("checkBoxWordWrap")
        self.verticalLayout_4.addWidget(self.checkBoxWordWrap)
        self.checkBoxDisplayTime = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxDisplayTime.setObjectName("checkBoxDisplayTime")
        self.verticalLayout_4.addWidget(self.checkBoxDisplayTime)
        self.checkBoxDisplayRecTime = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxDisplayRecTime.setObjectName("checkBoxDisplayRecTime")
        self.verticalLayout_4.addWidget(self.checkBoxDisplayRecTime)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.radioButtonSendASCII = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButtonSendASCII.setChecked(True)
        self.radioButtonSendASCII.setObjectName("radioButtonSendASCII")
        self.horizontalLayout_11.addWidget(self.radioButtonSendASCII)
        self.radioButtonSendHex = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButtonSendHex.setObjectName("radioButtonSendHex")
        self.horizontalLayout_11.addWidget(self.radioButtonSendHex)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.checkBoxRepeatSend = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBoxRepeatSend.setObjectName("checkBoxRepeatSend")
        self.horizontalLayout_12.addWidget(self.checkBoxRepeatSend)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_12.addWidget(self.spinBox)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.horizontalLayout_16.addLayout(self.verticalLayout_6)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_8.addWidget(self.line_2)
        self.line_3 = QtWidgets.QFrame(self.groupBox_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_8.addWidget(self.line_3)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setStyleSheet("color: rgb(164, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.labelRecCount = QtWidgets.QLabel(self.groupBox_2)
        self.labelRecCount.setStyleSheet("color: rgb(204, 0, 0);")
        self.labelRecCount.setObjectName("labelRecCount")
        self.horizontalLayout_8.addWidget(self.labelRecCount)
        self.line_4 = QtWidgets.QFrame(self.groupBox_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_8.addWidget(self.line_4)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setStyleSheet("color: rgb(32, 74, 135);")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.labelSendCount = QtWidgets.QLabel(self.groupBox_2)
        self.labelSendCount.setStyleSheet("color: rgb(32, 74, 135);")
        self.labelSendCount.setObjectName("labelSendCount")
        self.horizontalLayout_8.addWidget(self.labelSendCount)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.textBrowserRec = QtWidgets.QTextBrowser(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowserRec.sizePolicy().hasHeightForWidth())
        self.textBrowserRec.setSizePolicy(sizePolicy)
        self.textBrowserRec.setMinimumSize(QtCore.QSize(600, 0))
        self.textBrowserRec.setMaximumSize(QtCore.QSize(600, 16777215))
        self.textBrowserRec.setObjectName("textBrowserRec")
        self.verticalLayout_2.addWidget(self.textBrowserRec)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.lineEditAimIp = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEditAimIp.setObjectName("lineEditAimIp")
        self.horizontalLayout_9.addWidget(self.lineEditAimIp)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.lineEditAimPort = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEditAimPort.setObjectName("lineEditAimPort")
        self.horizontalLayout_9.addWidget(self.lineEditAimPort)
        self.pushButtonPing = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonPing.setObjectName("pushButtonPing")
        self.horizontalLayout_9.addWidget(self.pushButtonPing)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.textEditSend = QtWidgets.QTextEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditSend.sizePolicy().hasHeightForWidth())
        self.textEditSend.setSizePolicy(sizePolicy)
        self.textEditSend.setMinimumSize(QtCore.QSize(600, 120))
        self.textEditSend.setMaximumSize(QtCore.QSize(600, 120))
        self.textEditSend.setObjectName("textEditSend")
        self.verticalLayout_2.addWidget(self.textEditSend)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButtonSend = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonSend.setObjectName("pushButtonSend")
        self.horizontalLayout_7.addWidget(self.pushButtonSend)
        self.pushButtonClear = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonClear.setObjectName("pushButtonClear")
        self.horizontalLayout_7.addWidget(self.pushButtonClear)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_16.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 957, 28))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.comboBoxProtocal.currentIndexChanged['int'].connect(MainWindow.on_comboBoxProtocal_currentIndexChanged)
        self.comboBoxMode.currentIndexChanged['int'].connect(MainWindow.on_comboBoxMode_currentIndexChanged)
        self.checkBoxWordWrap.clicked['bool'].connect(MainWindow.on_checkBoxWordWrap_clicked)
        self.checkBoxDisplayTime.clicked['bool'].connect(MainWindow.on_checkBoxDisplayTime_clicked)
        self.checkBoxDisplayRecTime.clicked['bool'].connect(MainWindow.on_checkBoxDisplayRecTime_clicked)
        self.checkBoxRepeatSend.clicked['bool'].connect(MainWindow.on_checkBoxRepeatSend_clicked)
        self.radioButtonSendASCII.clicked.connect(MainWindow.on_radioButtonSendASCII_clicked)
        self.radioButtonSendHex.clicked.connect(MainWindow.on_radioButtonSendHex_clicked)
        self.radioButtonRecASCII.clicked.connect(MainWindow.on_radioButtonRecASCII_clicked)
        self.radioButtonRecHex.clicked.connect(MainWindow.on_radioButtonRecHex_clicked)
        self.spinBox.valueChanged['int'].connect(MainWindow.on_spinBoxTime_valueChanged)
        self.pushButtonConnect.clicked.connect(MainWindow.on_pushButtonConnect_click)
        self.pushButtonPing.clicked.connect(MainWindow.on_pushButtonPing_click)
        self.pushButtonDisconnect.clicked.connect(MainWindow.on_pushButtonDisconnect_click)
        self.pushButtonSend.clicked.connect(MainWindow.on_pushButtonSend_clicked)
        self.pushButtonClear.clicked.connect(MainWindow.on_pushButtonClear_clicked)
        self.pushButtonWriteIp.clicked.connect(MainWindow.on_pushButtonWriteIp_clicked)
        self.pushButtonAppIp.clicked.connect(MainWindow.on_pushButtonAppIp_clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Configuration"))
        self.label_4.setText(_translate("MainWindow", "Protocal:    "))
        self.comboBoxProtocal.setItemText(0, _translate("MainWindow", "TCP/IP"))
        self.comboBoxProtocal.setItemText(1, _translate("MainWindow", "UDP"))
        self.label_5.setText(_translate("MainWindow", "Mode:         "))
        self.comboBoxMode.setItemText(0, _translate("MainWindow", "Server"))
        self.comboBoxMode.setItemText(1, _translate("MainWindow", "Client"))
        self.label_11.setText(_translate("MainWindow", "Devices:     "))
        self.label_2.setText(_translate("MainWindow", "Local IP:     "))
        self.label_3.setText(_translate("MainWindow", "Local Port:"))
        self.pushButtonConnect.setText(_translate("MainWindow", "Connect"))
        self.pushButtonDisconnect.setText(_translate("MainWindow", "Disconnect"))
        self.pushButtonWriteIp.setText(_translate("MainWindow", "Write IP"))
        self.pushButtonAppIp.setText(_translate("MainWindow", "Application IP"))
        self.groupBoxClientList.setTitle(_translate("MainWindow", "Clients List"))
        item = self.tableWidgetClientList.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "#"))
        item = self.tableWidgetClientList.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "IP"))
        item = self.tableWidgetClientList.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Port"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Received Configuration"))
        self.radioButtonRecASCII.setText(_translate("MainWindow", "ASCII"))
        self.radioButtonRecHex.setText(_translate("MainWindow", "Hex"))
        self.checkBoxWordWrap.setText(_translate("MainWindow", "Word Wrap"))
        self.checkBoxDisplayTime.setText(_translate("MainWindow", "Display Send Time"))
        self.checkBoxDisplayRecTime.setText(_translate("MainWindow", "Display Received Time"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Send Configuration"))
        self.radioButtonSendASCII.setText(_translate("MainWindow", "ASCII"))
        self.radioButtonSendHex.setText(_translate("MainWindow", "Hex"))
        self.checkBoxRepeatSend.setText(_translate("MainWindow", "Repeat Send"))
        self.label_10.setText(_translate("MainWindow", "ms"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Text Area"))
        self.label.setText(_translate("MainWindow", "S/R Count:"))
        self.label_6.setText(_translate("MainWindow", "Received Bytes:"))
        self.labelRecCount.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "Send Bytes:"))
        self.labelSendCount.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "Target IP:"))
        self.label_9.setText(_translate("MainWindow", "Target Port:"))
        self.lineEditAimPort.setText(_translate("MainWindow", "5220"))
        self.pushButtonPing.setText(_translate("MainWindow", "Ping"))
        self.pushButtonSend.setText(_translate("MainWindow", "Send"))
        self.pushButtonClear.setText(_translate("MainWindow", "Clear"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
