# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/carlos/workspace/TINY_NETWORK_TOOLS_PYQT5/uiform/MainUi.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(952, 579)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.comboBoxProtocal = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxProtocal.setObjectName("comboBoxProtocal")
        self.comboBoxProtocal.addItem("")
        self.comboBoxProtocal.addItem("")
        self.horizontalLayout.addWidget(self.comboBoxProtocal)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.comboBoxMode = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxMode.setObjectName("comboBoxMode")
        self.comboBoxMode.addItem("")
        self.comboBoxMode.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBoxMode)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEditLocalIp = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditLocalIp.setObjectName("lineEditLocalIp")
        self.horizontalLayout_3.addWidget(self.lineEditLocalIp)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lineEditLocalPort = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditLocalPort.setObjectName("lineEditLocalPort")
        self.horizontalLayout_4.addWidget(self.lineEditLocalPort)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButtonConnect = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonConnect.setObjectName("pushButtonConnect")
        self.horizontalLayout_5.addWidget(self.pushButtonConnect)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButtonPing = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonPing.setObjectName("pushButtonPing")
        self.horizontalLayout_6.addWidget(self.pushButtonPing)
        self.pushButtonDisconnect = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonDisconnect.setObjectName("pushButtonDisconnect")
        self.horizontalLayout_6.addWidget(self.pushButtonDisconnect)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.radioButtonRecASCII = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButtonRecASCII.setObjectName("radioButtonRecASCII")
        self.horizontalLayout_10.addWidget(self.radioButtonRecASCII)
        self.radioButtonRecHex = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButtonRecHex.setObjectName("radioButtonRecHex")
        self.horizontalLayout_10.addWidget(self.radioButtonRecHex)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_4.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_4.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_4.addWidget(self.checkBox_3)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.radioButtonSendASCII = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButtonSendASCII.setObjectName("radioButtonSendASCII")
        self.horizontalLayout_11.addWidget(self.radioButtonSendASCII)
        self.radioButtonSendHex = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButtonSendHex.setObjectName("radioButtonSendHex")
        self.horizontalLayout_11.addWidget(self.radioButtonSendHex)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.checkBoxRepeatSend = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBoxRepeatSend.setObjectName("checkBoxRepeatSend")
        self.horizontalLayout_12.addWidget(self.checkBoxRepeatSend)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_12.addWidget(self.spinBox)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.horizontalLayout_13.addLayout(self.verticalLayout_6)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_8.addWidget(self.line_2)
        self.line_3 = QtWidgets.QFrame(self.groupBox_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_8.addWidget(self.line_3)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setStyleSheet("color: rgb(164, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.labelRecCount = QtWidgets.QLabel(self.groupBox_2)
        self.labelRecCount.setStyleSheet("color: rgb(204, 0, 0);")
        self.labelRecCount.setObjectName("labelRecCount")
        self.horizontalLayout_8.addWidget(self.labelRecCount)
        self.line_4 = QtWidgets.QFrame(self.groupBox_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_8.addWidget(self.line_4)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setStyleSheet("color: rgb(32, 74, 135);")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.labelSendCount = QtWidgets.QLabel(self.groupBox_2)
        self.labelSendCount.setStyleSheet("color: rgb(32, 74, 135);")
        self.labelSendCount.setObjectName("labelSendCount")
        self.horizontalLayout_8.addWidget(self.labelSendCount)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.textBrowserRec = QtWidgets.QTextBrowser(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowserRec.sizePolicy().hasHeightForWidth())
        self.textBrowserRec.setSizePolicy(sizePolicy)
        self.textBrowserRec.setMinimumSize(QtCore.QSize(600, 0))
        self.textBrowserRec.setMaximumSize(QtCore.QSize(600, 16777215))
        self.textBrowserRec.setObjectName("textBrowserRec")
        self.verticalLayout_3.addWidget(self.textBrowserRec)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.lineEditAimIp = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEditAimIp.setObjectName("lineEditAimIp")
        self.horizontalLayout_9.addWidget(self.lineEditAimIp)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.lineEditAimPort = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEditAimPort.setObjectName("lineEditAimPort")
        self.horizontalLayout_9.addWidget(self.lineEditAimPort)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.textEditSend = QtWidgets.QTextEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditSend.sizePolicy().hasHeightForWidth())
        self.textEditSend.setSizePolicy(sizePolicy)
        self.textEditSend.setMinimumSize(QtCore.QSize(600, 120))
        self.textEditSend.setMaximumSize(QtCore.QSize(600, 120))
        self.textEditSend.setObjectName("textEditSend")
        self.verticalLayout_3.addWidget(self.textEditSend)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButtonSend = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonSend.setObjectName("pushButtonSend")
        self.horizontalLayout_7.addWidget(self.pushButtonSend)
        self.pushButtonClear = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonClear.setObjectName("pushButtonClear")
        self.horizontalLayout_7.addWidget(self.pushButtonClear)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_13.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 952, 28))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.pushButtonConnect.clicked.connect(self.pushButtonConnect.click)
        self.comboBoxProtocal.currentIndexChanged['int'].connect(self.comboBoxProtocal.setCurrentIndex)
        self.comboBoxMode.currentIndexChanged['int'].connect(self.comboBoxMode.setCurrentIndex)
        self.pushButtonConnect.clicked.connect(self.pushButtonConnect.click)
        self.pushButtonPing.clicked.connect(self.pushButtonPing.click)
        self.pushButtonDisconnect.clicked.connect(self.pushButtonDisconnect.click)
        self.radioButtonRecASCII.clicked['bool'].connect(self.radioButtonRecASCII.setChecked)
        self.radioButtonRecHex.toggled['bool'].connect(self.radioButtonRecHex.setChecked)
        self.checkBox.clicked['bool'].connect(self.checkBox.setChecked)
        self.checkBox_2.clicked['bool'].connect(self.checkBox_2.setChecked)
        self.checkBox_3.clicked['bool'].connect(self.checkBox_3.setChecked)
        self.radioButtonSendASCII.clicked['bool'].connect(self.radioButtonSendASCII.setChecked)
        self.radioButtonSendHex.clicked['bool'].connect(self.radioButtonSendHex.setChecked)
        self.checkBoxRepeatSend.clicked['bool'].connect(self.checkBoxRepeatSend.setChecked)
        self.spinBox.valueChanged['int'].connect(self.spinBox.setValue)
        self.pushButtonSend.clicked['bool'].connect(self.pushButtonSend.click)
        self.pushButtonClear.clicked['bool'].connect(self.pushButtonClear.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Configuration"))
        self.label_4.setText(_translate("MainWindow", "Protocal:   "))
        self.comboBoxProtocal.setItemText(0, _translate("MainWindow", "TCP/IP"))
        self.comboBoxProtocal.setItemText(1, _translate("MainWindow", "UDP"))
        self.label_5.setText(_translate("MainWindow", "Mode:         "))
        self.comboBoxMode.setItemText(0, _translate("MainWindow", "Server"))
        self.comboBoxMode.setItemText(1, _translate("MainWindow", "Client"))
        self.label_2.setText(_translate("MainWindow", "Local IP:     "))
        self.label_3.setText(_translate("MainWindow", "Local Port:"))
        self.pushButtonConnect.setText(_translate("MainWindow", "Connect"))
        self.pushButtonPing.setText(_translate("MainWindow", "Ping"))
        self.pushButtonDisconnect.setText(_translate("MainWindow", "Disconnect"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Received Configuration"))
        self.radioButtonRecASCII.setText(_translate("MainWindow", "ASCII"))
        self.radioButtonRecHex.setText(_translate("MainWindow", "Hex"))
        self.checkBox.setText(_translate("MainWindow", "Word Wrap"))
        self.checkBox_2.setText(_translate("MainWindow", "Display Send Time"))
        self.checkBox_3.setText(_translate("MainWindow", "Display Received Time"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Send Configuration"))
        self.radioButtonSendASCII.setText(_translate("MainWindow", "ASCII"))
        self.radioButtonSendHex.setText(_translate("MainWindow", "Hex"))
        self.checkBoxRepeatSend.setText(_translate("MainWindow", "Repeat Send"))
        self.label_10.setText(_translate("MainWindow", "ms"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Text Area"))
        self.label.setText(_translate("MainWindow", "S/R Count:"))
        self.label_6.setText(_translate("MainWindow", "Received Bytes:"))
        self.labelRecCount.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "Send Bytes:"))
        self.labelSendCount.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "Aim IP:"))
        self.label_9.setText(_translate("MainWindow", "Aim Port:"))
        self.pushButtonSend.setText(_translate("MainWindow", "Send"))
        self.pushButtonClear.setText(_translate("MainWindow", "Clear"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
